### ISSUE TITLE
Document use of Korrel8r.Spec.Config field.

### ISSUE THREAD

**Issue by alanconway** [korrel8r/korrel8r#69]
Need to explain
- configuration file format and meaning
  - source: https://github.com/korrel8r/korrel8r/blob/main/pkg/config/types.go#L9
  - API doc: https://pkg.go.dev/github.com/korrel8r/korrel8r@latest/pkg/config#Config 
- running directly as an executable:
  - specify alternate config files via --config flag
  - note that config file can "include" other config files 
- running as a k8s resource via Korrel8r resource
  -  Primary configuration is part of the resource: field .spec.config
  - additional config files can be added via a ConfigMap (details & example)
  - standard config files are built-into the image (/etc/korrelr8/..., need to list available fragments and paths)

**Comment by abrennan89** [comment]
API doc link says "latest is not a valid version" but this one works: https://pkg.go.dev/github.com/korrel8r/korrel8r/pkg/config#Config

**Comment by alanconway** [comment]
@abrennan89 the pkg.go.doc doc site only generates docs for "released" versions, i.e. ones having a vx.y.z tag or branch.

You can read the latest directly from [Go source](https://github.com/korrel8r/korrel8r/blob/main/pkg/config/types.go)  - the same text, just not as pretty. Look for // comments directly before each `func`, `type` or `package` declaration with no intervening newlines.

You can [install pkgsite](https://pkg.go.dev/golang.org/x/pkgsite/cmd/pkgsite) yourself - that's the tool used by pkg.go.doc to format the docs. Then you can view any Go source code including your own private edits.

If/when you decide to contribute back improvements for the API doc, you'll can edit the source comments  & preview using pkgsite. The [formatting rules](https://tip.golang.org/doc/comment) are minimal and simple, markdown-ish but a very restrictred subset.

**Comment by abrennan89** [comment]
Some of this is now documented per https://github.com/korrel8r/korrel8r/pull/79
