### ISSUE TITLE
[Documentation] Alerts to logs won't be available if the logs are excluded from collection.

### ISSUE THREAD

**Issue by QiaolingTang** [korrel8r/korrel8r#72]
If the logs of the pod which makes an alert firing are excluded from collection, the link `See related logs` is not available, for example: CollectorHighErrorRate.

**Comment by alanconway** [comment]
Can't fix this, @abrennan89  this deserves a mention in the console documentation: 
- the "related logs" link will not be shown if no related logs have been collected
- the cluster logging operator does not collect its own logs, to avoid circular "infinite loop" problems.

**Comment by abrennan89** [comment]
@alanconway these are both already mentioned in https://korrel8r.github.io/korrel8r/#_troubleshooting I think
