### ISSUE TITLE
Authentication and Authorization for restricted access.

### ISSUE THREAD

**Issue by alanconway** [korrel8r/korrel8r#73]
Korrel8r reads multiple data stores, containing potentially sensitive information, with different authn/authz rules. In the initial versions this was done by using a "read everything" service account, which is a security problem.

When run as a REST service, korrel8r should not use a special service account, it should foward auth tokens provided in the REST request to "impersonate" the caller of the API so it can retrieve only data that the caller is allowed to see.

Related: https://issues.redhat.com/browse/COO-232

**Comment by alanconway** [comment]
Initial PR  #131 
Caused problems with console integration, need to investigate andn fix.
@shwetaap can you add a comment on the problems you had trying to make this work with COO?

**Comment by alanconway** [comment]
This was supposed to be fixed by
716838e * fix #120: Forward Authorization headers from REST requests to stores.

But testing shows there are some problems. To reproduce do:
```
oc apply https://github.com/korrel8r/demos/blob/main/kdc-texas/bad-deployment.yaml
```
and open Observe>Alerting>KubePodCrashLooping
the graph is populated sucessfully but the korrel8r logs some errors like
```
korrel8r 22:20:03 "msg"="abort request" "error"="failed to query rules from Prometheus API: client_error: client error: 401" "url"="/api/v1alpha1/lists/goals" "code"=500 "errors"="Error #01: failed to query rules from Prometheus API: client_error: client error: 401\n"
korrel8r 22:20:41 "level"=2 "msg"="Get error" "rule"="K8sSrcToNetflow" "start"="k8s:Pod.v1." "goal"="netflow:network" "query"="netflow:network:{SrcK8S_Type=\"Pod\", SrcK8S_Namespace=\"default\"} | json | SrcK8S_Name=\"bad-config-deployment-56b4997dd9-qk4q2\"" "error"="403 Forbidden: {\"error\":\"You don't have permission to access this tenant\",\"errorType\":\"observatorium-api\",\"status\":\"error\"}\n"
korrel8r 22:20:50 "level"=2 "msg"="Get error" "rule"="PodToLogs" "start"="k8s:Pod.v1." "goal"="log:infrastructure" "query"="log:infrastructure:{kubernetes_namespace_name=\"default\",kubernetes_pod_name=\"bad-config-deployment-56b4997dd9-qk4q2\"}" "error"="403 Forbidden: {\"error\":\"You don't have permission to access this tenant\",\"errorType\":\"observatorium-api\",\"status\":\"error\"}\n"

**Comment by alanconway** [comment]
FYI @shwetaap - if you have any more info please comment.

**Comment by shwetaap** [comment]
Yes! this is the error that I ran into as well. Thanks for adding it here.
