### ISSUE TITLE
Unable to build images in case of docker

### ISSUE THREAD

**Issue by vprashar2929** [korrel8r/korrel8r#95]
When using make target like `image-build` in the case of docker it is unable to build images as docker doesn't respect `Containerfile` For docker It should be a `Dockerfile`. 

For ref: https://github.com/docker/cli/issues/3251#issuecomment-1063338859

**Comment by alanconway** [comment]
You can use `dockerfile -f Containerfile` - can you test that? If it works then please do a PR for the makefile to include `-f Containerfile` in all cases, since it will work with podman also.

**Comment by vprashar2929** [comment]
I checked and docker build -f Containerfile works. Will raise PR to include `-f Containerfile` Thanks for the suggestion🙇🏼‍♂️
